# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b32007d6fcce6f42f5bc13b430f3dbd6f6743cf768cd3febafe9db9415564cef6aeaa42235c46b436e56896004e686be98e8a7c36281c39772386e3db5113c

test:
  secret_key_base: d45e219a7d5a97d7c24d05bb2cfc669ae3d40351d452a9adc20b1ad9398ee7ebfcb102c20e68eda6fcd8348f99962b2514d997871f73bbb8e4b36ca50c9ab991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
